defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

run:
  output_file: results/adaptive.json

ga:
  _target_: src.algos.adaptive.ImprovedAdaptiveGA
  population_size: 350
  iterations: 1000
  crossover_rate: 0.8708708889922567
  mutation_rate: 0.597477405673311
  alpha: 0.009801927028492408
  lambda_min: 0.0
  lambda_max: 1.0
  epsilon: 1e-5
  gamma: 0.2
  tournament_size: 3
  attenuate_reward: true
  stagnation_limit: 28
  immigrant_rate: 0.18181347228426545
  verbose: false
