defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

run:
  output_file: results/adaptive_gea_scenario_3.json

ga:
  _target_: src.algos.adaptive.ImprovedAdaptiveGEAScenario3
  population_size: 350
  iterations: 1000
  crossover_rate: 0.7119312779954151
  mutation_rate: 0.5376631237490226
  injection_rate: 0.2579589358921035
  alpha: 0.0010994444460392775
  lambda_min: 0.25917668448044195
  lambda_max: 1.6090662195411438
  epsilon: 1e-5
  stagnation_limit: 41
  immigrant_rate: 0.0854003476392007
  verbose: false
