defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

run:
  output_file: results/adaptive_gea_scenario_1.json

ga:
  _target_: src.algos.adaptive.ImprovedAdaptiveGEAScenario1
  population_size: 350
  iterations: 1000
  crossover_rate: 0.7792025678325523
  mutation_rate: 0.587135462861959
  rc_rate: 0.5756888179314985
  alpha: 0.038424719387308355
  lambda_min: 0.0
  lambda_max: 1.0
  epsilon: 1e-5
  gamma: 0.2
  tournament_size: 3
  attenuate_reward: true
  stagnation_limit: 11
  immigrant_rate: 0.14334472200479442
  verbose: false
