defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

ga:
  _target_: src.algos.ga_adaptive.AdaptiveGA
  population_size: 350
  iterations: 1000
  crossover_rate: 0.7
  mutation_rate: 0.3
  alpha: 0.01
  lambda_min: 0.4
  lambda_max: 1.5
  epsilon: 1e-5
  verbose: false
