defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

ga:
  _target_: src.algos.ga_pso.ParticleSwarm
  population_size: 350
  iterations: 1000
  inertia_weight: 0.5067528830285765
  cognitive_weight: 0.10153099605463807
  social_weight: 0.42322470712713445
  stagnation_limit: 20
  immigrant_rate: 0.10775761191824078
  verbose: false
