defaults:
  - datasets: common
  - run: common
  - hydra: common
  - _self_

ga:
  _target_: src.algos.ga_sa.SimulatedAnnealing
  population_size: 1
  iterations: 1000
  initial_temperature: 194.89569674489042
  cooling_rate: 0.9445885285679331
  min_temperature: 0.002985663916586654
  verbose: false
