defaults:
  - datasets: common
  - run: common
  - hydra: common
  - _self_

ga:
  _target_: src.algos.ga_sa.SimulatedAnnealing
  population_size: 1
  iterations: 1000
  initial_temperature: 50.0
  cooling_rate: 0.97
  min_temperature: 1e-3
  verbose: false
