defaults:
  - datasets: common
  - components@ga: common
  - run: common
  - hydra: common
  - _self_

ga:
  _target_: src.algos.ga_standard.StandardGA
  population_size: 350
  iterations: 1000
  crossover_rate: 0.7
  mutation_rate: 0.3
