import math

import numpy as np

from src.algos.base import BaseGA
from src.costs import evaluate_permutation_delta_batch
from src.operators.crossover import choose_crossover
from src.operators.mutations import choose_mutation


class HybridGAPSO(BaseGA):
    """Juang (2004). Each generation, the population is ranked by cost and split in two:
    the better-ranked `pso_fraction` undergo a PSO-style move (exploitation, pulled toward
    their own personal best and the swarm's global best -- see src/algos/pso.py for the
    discrete crossover/mutation encoding of that pull); the rest are regenerated by ordinary
    GA crossover/mutation (exploration). An elitist replacement then guarantees the
    swarm's best-ever solution survives into the next generation, as in the original paper.

    Particle identity (self.particles/self.personal_best) is tracked independently of
    self.population's ordering for the same reason as in ParticleSwarm: BaseGA.run() re-sorts
    self.population by cost after every step(), which would scramble a particle's identity if
    it were tracked by position in that list instead.
    """

    def __init__(
        self,
        model,
        population_size=350,
        iterations=1000,
        pso_fraction=0.5,
        inertia_weight=0.4,
        cognitive_weight=0.3,
        social_weight=0.3,
        crossover_rate=0.7,
        mutation_rate=0.3,
        repair_class=None,
        selector=None,
        stagnation_limit=30,
        immigrant_rate=0.1,
        verbose=False,
    ):
        super().__init__(
            model,
            population_size,
            iterations,
            repair_class=repair_class,
            selector=selector,
            stagnation_limit=stagnation_limit,
            immigrant_rate=immigrant_rate,
            verbose=verbose,
        )

        self.pso_fraction = pso_fraction

        total_weight = inertia_weight + cognitive_weight + social_weight
        self.inertia_weight = inertia_weight / total_weight
        self.cognitive_weight = cognitive_weight / total_weight
        self.social_weight = social_weight / total_weight

        self.crossover_rate = crossover_rate
        self.mutation_rate = mutation_rate

        self.particles = []
        self.personal_best = []

    def initialize_population(self) -> None:
        super().initialize_population()
        self.particles = list(self.population)
        self.personal_best = list(self.population)

    def _pso_update(self, idx, gbest) -> None:
        new_perms = []
        for i in idx:
            position = self.particles[i]
            pbest = self.personal_best[i]

            r = np.random.random()
            if r < self.inertia_weight:
                candidate = choose_mutation(position.permutation, self.model)
            elif r < self.inertia_weight + self.cognitive_weight:
                (child1, _), _ = choose_crossover((position, pbest), self.model)
                candidate = child1
            else:
                (child1, _), _ = choose_crossover((position, gbest), self.model)
                candidate = child1
            new_perms.append(candidate)

        repaired = self.repair_batch_wrapper(np.array(new_perms))
        baselines = [self.particles[i] for i in idx]
        updated = evaluate_permutation_delta_batch(baselines, repaired, self.model)
        self.logger.record_nfe(len(idx))

        for i, candidate in zip(idx, updated):
            self.particles[i] = candidate
            if candidate.cost < self.personal_best[i].cost:
                self.personal_best[i] = candidate

    def _ga_update(self, idx) -> None:
        # Borrow BaseGA's crossover/mutate/select_from_pool by temporarily pointing
        # self.population at just this generation's GA-assigned subset, then restoring it --
        # those methods are written against "the population" as a whole, and this subset is
        # exactly that for the duration of this call.
        original_population = self.population
        self.population = [self.particles[i] for i in idx]

        probs = self.compute_selection_probabilities()
        n = len(idx)
        ncrossover = int(2 * round((self.crossover_rate * n) / 2))
        nmutation = int(math.floor(self.mutation_rate * n))

        offspring = [child for child, _ in self.crossover(probs, ncrossover)]
        mutations = [child for child, _ in self.mutate(nmutation)]

        pool = self.population + offspring + mutations
        selected = self.selector.select_from_pool(pool, n, self.progress)

        self.population = original_population

        for slot, ind in zip(idx, selected):
            self.particles[slot] = ind
            if ind.cost < self.personal_best[slot].cost:
                self.personal_best[slot] = ind

    def step(self) -> None:
        gbest = self.best_solution
        n = self.population_size
        n_pso = int(round(self.pso_fraction * n))

        order = sorted(range(n), key=lambda i: self.particles[i].cost)
        pso_idx = order[:n_pso]
        ga_idx = order[n_pso:]

        if pso_idx:
            self._pso_update(pso_idx, gbest)
        if ga_idx:
            self._ga_update(ga_idx)

        # Elitist guarantee (Juang, 2004): the swarm's best-ever solution always survives
        # into the next generation, even if every particle's own move this round was a loss.
        worst_idx = max(range(n), key=lambda i: self.particles[i].cost)
        if gbest is not None and gbest.cost < self.particles[worst_idx].cost:
            self.particles[worst_idx] = gbest
            if gbest.cost < self.personal_best[worst_idx].cost:
                self.personal_best[worst_idx] = gbest

        immigrants = self.maybe_generate_immigrants()
        if immigrants:
            replace_idx = np.random.choice(n, size=len(immigrants), replace=False)
            for idx, immigrant in zip(replace_idx, immigrants):
                self.particles[idx] = immigrant
                self.personal_best[idx] = immigrant

        self.population = list(self.particles)
